logging:
  level:
    org.springframework: info

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  datasource:
    url: jdbc:h2:mem:jsonplaceholder
    username: sa
    driverClassName: org.h2.Driver
    password:
  flyway:
    user: root
    password: root
    url: jdbc:h2:mem:jsonplaceholder
    enabled: false
