logging:
  level:
    org.springframework: info

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create
    generate-ddl: true

  datasource:
    url: jdbc:mysql://localhost:3306/jsonplaceholdertest
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
  flyway:
    user: root
    password: root
    url: jdbc:mysql://localhost:3306/jsonplaceholdertest
    enabled: false
