openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  version: 1.0.11
servers:
  - url: https://jsonplaceholder.swagger.io/api/v3
tags:
  - name: user
    description: Operations about user
  - name: todos
    description: Operations about todos
paths:
  /saveAllUser:
    get:
      tags:
        - user
      summary: Save all user from the jsonplaceholder api
      operationId: createUser
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Leanne Graham"
        username:
          type: string
          minLength: 5
          maxLength: 20
          example: "Bret"
        address:
          $ref: '#/components/schemas/Address'
        phone:
          type: string
          example: 1-463-123-4447
        website:
          type: string
          example: ramiro.info
        company:
          $ref: '#/components/schemas/Company'
    Address:
      type: object
      properties:
        street:
          type: string
          example: Kulas Light
        suite:
          type: string
          example: Apt. 556
        city:
          type: string
          example: Gwenborough
        zipcode:
          type: string
          example: 59590-4157
        geo:
          $ref: '#/components/schemas/Geo'
    Geo:
      type: object
      properties:
        lat:
          type: number
          format: double
          example: -68.6102
        lng:
          type: number
          format: double
          example: -47.0653
    Company:
      type: object
      properties:
        name:
          type: string
          example: Romaguera-Jacobson
        catchPhrase:
          type: string
          example: Face to face bifurcated interface
        bs:
          type: string
          example: e-enable strategic applications
    Todos:
      type: object
      properties:
        userId:
          type: integer
          format: int64
          example: 1
        id:
          type: integer
          format: int64
          example: 1
        title:
          type: string
          example: delectus aut autem
        completed:
          type: boolean